#+TITLE: 内置类型

* 真假判断
   除下面情况外都为True：
  - None
  - False
  - 任何形式的数值0，如0、0.0、0j。
  - 空的sequence，如''、()、[]。
  - 空的map，如{}。
  - 自定义类中有__bool__和__len()__方法，且实例的此方法返回0或布尔值
    False。

	操作符（Operations）和内置函数如果返回布尔型，要么返回1或True作为
    “真”，要么返回0或False作为“假”。

	*注意* ：or和and操作符总是将其一个operands作为返回值。

* 布尔值操作-and、or、not
   下表按有限级排序：

   | Operation | 结果                                    | 注意 |
   |-----------+-----------------------------------------+------|
   | x or y    | 如果x为false，则返回y，否则返回x        | (1)  |
   | x an y    | 如果x为false，则返回x，否则返回y        | (2)  |
   | not x     | 如果x为false，则返回True，否则返回False | (3)  |

   注意点：

   1. 只有x为假，才计算y。
   2. 只有x为真，才计算y。
   3. 三者中not的优先级最低，所以not a == b相当于not (a == b)，而a ==
      not b为语法错误。

* 比较
   Python有8个比较操作符，优先级相同，不过都比布尔值操作符高。比较操作
   可任意组合，如x < y <= z等价于x < y and y <= z（与C不同），不过y只
   计算一次，且如果x < y 为加，不计算z，直接返回False。

   | 操作符 | 含义         |
   |--------+--------------|
   | <      | 小于         |
   | <=     | 小于等于     |
   | >      | 大于         |
   | >=     | 大于等于     |
   | ==     | 等于         |
   | !=     | 不等于       |
   | is     | 对象完全相同 |
   | is not | 不为相同对象 |

   除不同类型的数字外，所有不同对象之间的比较都返回False。

   除非声明__eq__()方法，相同类的不同实例不相等。

   相同类的不同实例不能排序，除非有定
   义__lt__()、__le__()、__gt__()和__ge__()方法。（如需只进行比较，定
   义__lt__()和__gt__()方法就足够。）

   is和is not不能定制，可接受任意2个对象，从不返回错误。

   in 和 not in两个操作符具有比较操作符的相同优先级，仅支持sequence类
   型。

* 数字类型-int、float、complex
   一共有3种数字类型：整型、浮点型和复数。此外，布尔型是整型的子类型。
   整型精度无限，浮点型通常与C中的double型精度相同（可使用
   sys.float_info变量查看）。复数分实部和虚部（都为浮点型），如果z为复
   数，则可使用z.real和z.image分别获取实部和虚部。数字后添加j或J可转变
   为虚数。

   Python支持不同的数字类型一起计算。多个类型一起计算时，“窄类型”转换
   为“宽类型”，整型比浮点型窄，浮点型比复数窄。数字之间的比较也使用相
   同方法。

   下表为除复数，所有数字类型都可使用的操作符，按优先级从低到高排序
   （所有数字操作符的优先级都比比较操作符低）。

   | 操作符          | 结果                         | 注意点 | 完整文档  |
   |-----------------+------------------------------+--------+-----------|
   | x + y           | 和                           |        |           |
   | x - y           | 差                           |        |           |
   | x * y           | 积                           |        |           |
   | x / y           | 商                           |        |           |
   | x // y          | x整除y的结果                 | (1)    |           |
   | x % y           | x / y的余值                  | (2)    |           |
   | -x              | 相反数                       |        |           |
   | +x              | 保持不变                     |        |           |
   | abs(x)          | x的绝对值或虚部              |        | abs()     |
   | int(x)          | 将x转换为整型                | (3)(6) | int()     |
   | float(x)        | 将x转换为浮点型              | (4)(6) | float()   |
   | complex(re, im) | 生成复数，img虚数部分默认为0 | (6)    | complex() |
   | c.conjugate()   | 复数c的共轭？                |        |           |
   | divmode(x, y)   | 相当于tuple(x // y, x % y)   | (2)    | divmode() |
   | pow(x, y)       | x的y次方                     | (5)    | pow()     |
   | x ** y          | x的y次方                     | (5)    |           |

   1. 结果无小数，不一定为整型。结果总是向负的最小值靠近：

	  #+BEGIN_EXAMPLE python
        >>> 1 // 2
        0
        >>> (-1) // 2
        -1
        >>> 1 // (-2)
        -1
        >>> (-1) // (-2)
        0
	  #+END_EXAMPLE

   2. 不适用于复数，而是使用abs()函数转换为浮点型。？？？

   3. 将浮点型转换为整数时，同C一样会“舍入”。参考math.floor()和
      math.ceil()函数。

   4. 浮点型可接受字符串“nan”和"inf"作为非数字和无线数，前面可带正负号。

   5. 如其他语言一样，Python规定pow(0,0)和0**0的值都为1。

   6. 可使用0-9和任何Unicode等价的字符。？？

   所有numbers.Real类型（即int和float类型）还可接受如下操作：

   | 操作          | 结果                                                  |
   |---------------+-------------------------------------------------------|
   | math.trunc(x) | 去除小数点后面内容                                    |
   | round(x[,n])  | 小数点后n个数，如果无第二个参数，相当于正真的四舍五入 |
   | math.floor(x) | <=x 的最大整数                                        |
   | math.ceil(x)  | >=x 的最小整数                                        |

** 整数位运算
	位运算只适用于整数。负数进行位运算时取反补码（以保证足够的bit防止
	计算时溢出）。

	位运算操作符优先级高于比较运算符，低于算术运算符；~运算符与加减运
	算符有相同优先级。

	下表为优先级从低到高的的位运算符：

    | 操作     | 结果 | 注意点 |
    |----------+------+--------|
    | x 竖线 y | 或   |        |
    | x ^ y    | XOR  |        |
    | x & y    | 和   |        |
    | x << n   | 左移 | (1)(2) |
    | x >> n   | 右移 | (1)(3) |
    | ~x       | 取反 |        |

	1. n为负数时返回ValueError错误
	2. 位左移相当于没有溢出检查的乘以pow(2,n)
	3. 位右移相当于没有溢出检查的除以pow(2,n)

** 整型的额外方法
*** int. *bit_length* ()
	 返回以二进制表示整数的位数：

	 #+BEGIN_EXAMPLE python
       >>> n = -37
       >>> bin(n)
       '-0b100101'
       >>> n.bit_length()
       6
	 #+END_EXAMPLE

	 等价于：

	 #+BEGIN_SRC python
       def bit_length(self):
           s = bin(self)
           s = s.lstrip('-0b')
           return len(s)
	 #+END_SRC

*** int. *to_bytes* (length,byteorder,*,signed=False)？？？
*** clasmethod int *from_bytes* (bytes,byteorder,*,signed=False)？？？
** 浮点型的额外方法
*** float. *as_integer_ratio* ()
*** float. *is_integer* ()
*** float. *hex* ()
*** classmethod float. *fromhex* (s)
** numeric类型哈希计算（Hashing）
* Iterator类型
   Python支持在容器（container）外面嵌套一个迭代层。此实现使用了2个不
   同的方法，帮助用户自定义类主持迭代。后面讨论的Sequence总是支持下面
   的迭代方法。

   容器对象需支持container. *__iter__* ()方法提供迭代支持，此方法： 返
   回一个迭代对象。

   迭代对象本身需支持iterator. *__iter__* ()和iterator. *__next__* ()
   方法。

** Generator类型
	如果容器对象有__iter__()方法，且为generator实现，则自动返回迭代对
	象，且支持__iter__()和__next__()方法。

* Sequence类型-list、tuple、range
   3个基本的Sequence类型为：链表、元组和范围。另外两个专门用于处理二进
   制数据（binary date）和文本字符串（text string）Sequence类型在专门
   章节讨论。
** 常用的Sequence操作符
	下表的操作对mutable和immutable都有效。其中s和t都是类型相同的
	Sequence，n、i和j都是整数索引，x？

	整个表中的优先级递增。in和not in具有相同的优先级，+和*的优先级同用
	于数字运算一样。

    | 操作符               | 结果                               | 注意点 |
    |----------------------+------------------------------------+--------|
    | x in s               | 如果x与s中某个元素equal，返回True  | (1)    |
    | x not in s           | 如果x与s中某个元素equal，返回False | (1)    |
    | s + t                | 将s和t连接                         | (6)(7) |
    | s * n 或 n * s       | 将s复制n次                         | (2)(7) |
    | s[i]                 | s中的第i个元素，第一个元素为s[0]   | (3)    |
    | s[i:j]               | 截取s中第i到j的元素                | (3)(4) |
    | s[i:j:k]             | 截取s中第i到j的元素，跨度为k       | (3)(5) |
    | len(s)               | s的元素个数                        |        |
    | min(s)               | s中最下的元素                      |        |
    | max(s)               | s中最大的元素                      |        |
    | s.index[x[, i[, j]]] | s中第一个x的索引（索引i后，j前）   | (8)    |
    | s.count(x)           | s中x的个数                         |        |

	同类型的sequence可做比较。比如链表和元组，为逐个比较其中的元素。即
	两个Sequence相等，则需对应位置的元素相等，且类型相同，长度相等。

	注意点：

	1. in和not in通常用来判断是否包含某元素，不过一些特殊的Sequence，
       如str、bytes和bytearray也可同样使用：

	   #+BEGIN_EXAMPLE python
         >>> 'gg' in 'egge'
         True
	   #+END_EXAMPLE

	2. n如果小于0，则作为0对待，返回相同类型的Sequence，但其中无元素。
       注意，复制s本身并不是正真复制，而是多次引用原来的元素：

	   #+BEGIN_EXAMPLE python
         >>> lists = [[]] * 3
         >>> lists
         [[], [], []]
         >>> lists[0].append(3)
         >>> lists
         [[3], [3], [3]]
	   #+END_EXAMPLE

	3. 如果i或j为负数，则相当于les(s)+i和len(s)+j。

	4. 截取s时，如果没有i，则i相当于0；如果没有j，则j相当于len(s)。如
       果i或j大于len(s)，则默认为len(s)；如果i >= j，则结果中没有任何
       元素。

	5. 使用步数k参数：相当于截取元素i、i+k、i+2k...，直到大于或等于
       j（不包含j）。k值不能为0，如果为None则默认为1。

	6. 拼接immutable类型的Sequence时，会生成新对象。意味着复制自身拼接
       时耗时按次方增加，如需使耗时线性等价可：

	   1. 如果是拼接str对象，可先链表再使用str.join()函数合成字符串；
          或者将其写入一个io.StringIO实例，最后再获取。

	   2. 如歌拼接bytes对象，可同字符串一样使用bytes.join()函数或
          io.BytesIO；或者使用bytearray，bytearray对象为mutable类型，
          效率更高。

	   3. 如果拼接元组，可转换为链表再操作。

	   4. 对于其他类型，参考相应文档。

	7. 如range这样的对象，不支持拼接和复制。

	8. 如果s中无元素x，则返回Valueerror错误。如果有i和j参数，则相当于
       s[i:j].index(x)，只是没有数据复制，且返回索引值相对于sequence的
       起始位置，而非截断的起始位置。

** Immutable Sequence类型
	immutable类型中有，而mutable类型中没有实现的唯一操作是hash()。

	此特性可使immutable类型，如元组，可作为字典(dict)的key值，或另存为
	set或frozenset。

	如果尝试hash含unhashable元素的immutable类型，则返回Typeerror错误。
	如：

	#+BEGIN_EXAMPLE python
      >>> hash((1,2,[2]))
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        TypeError: unhashable type: 'list'
	#+END_EXAMPLE

** Mutable Sequence类型
	下表为只有mutable类型才有的操作。其中s为mutable类型的实例，t为任何
	可迭代的对象，x?

    | 操作              | 结果                                                 | 注意点 |
    |-------------------+------------------------------------------------------+--------|
    | s[i]=x            | 使用x替换s中索引为i的元素                            |        |
    | s[i:j]=t          | 将s中i->j截断替换为可迭代对象t中的内容               |        |
    | del s[i:j]        | 与s[i:j]=[]同                                        |        |
    | s[i:j:k]=t        | 将截断对应位置上的元素逐个替换为t中的元素            | (1)    |
    | del s[i:j:k]      | 将截断s[i:j:k]从s中删除                              |        |
    | s.append(x)       | 将x添加到s末尾，相当于s[len(s):len(s)]=[x]           |        |
    | s.clear()         | 清除s中所有元素，相当于del s[:]                      | (5)    |
    | s.copy            | 复制s，相当于s[:]                                    | (5)    |
    | s.extend(t)或s+=t | 将t中的元素拼接到s后，基本上等价于s[len(s):len(s)]=t |        |
    | s *= n            | s自身复制n次                                         | (6)    |
    | s.insert(i, x)    | 将s中第i个元素变为x，等价于s[i:i]=x                  |        |
    | s.pop([i])        | 返回s中第i个元素，并将其删除                         | (2)    |
    | s.remove(x)       | 将s中出现的第一个x删除                               | (3)    |
    | s.reverse()       | 将s自身逆序。                                        | (4)    |

	注意点：

	1. t需与截断的长度相等。
	2. 可选参数i默认值为-1，即默认删除最后一个元素。
	3. 如果s中不存在元素x，则返回Valueerror错误。
	4. 为逆序大型sequence时的效率考虑，reverse()方法直接将该sequence逆
       序。为提醒使用者，故意不反悔逆序后的sequence。
	5. clear()和copy()方法是为了兼容不支持截断的mutable序列类型接口，
       如set和dict。
	6. n为整数，或有__index__()方法的对象。当n<=0时，清空。同上，复制
       自身并不是真正复制，而是复制reference：

	   #+BEGIN_EXAMPLE python
         >>> t = [[1],[2]]
         >>> t *= 2
         >>> t
         [[1], [2], [1], [2]]
         >>> t[0].append(1000)
         >>> t
         [[1, 1000], [2], [1, 1000], [2]]
	   #+END_EXAMPLE

** 链表（List）
	链表为mutable类型的sequence，一般用来存储相同类型的元素。

*** class *list* ([iterable])
	 构建链表有下面方法：

	 - 使用方括号构建空链表。
	 - 使用方括号，指定其中元素4用逗号隔开。如[a]、[a,b,c]。
	 - 或者为[x for x in iterable]的形式。
	 - 或者使用类型构造器：list()或list(iterable)。

	 使用最后一种方法，list构造链表时，新生成的链表中元素顺序同原来的
	 iterable相同。iterable可以是sequence、支持迭代的容器、或者是
	 iterator对象。 如果iterable本身就是链表，则是复制其reference。如
	 果没有参数，则返回空链表：

	 #+BEGIN_EXAMPLE python
       >>> a = [[1],[2]]
       >>> b = list(a)
       >>> b
       [[1], [2]]
       >>> b[0].append(100)
       >>> b
       [[1, 100], [2]]
       >>> a
       [[1, 100], [2]]
	 #+END_EXAMPLE

	 有许多其他操作符可生成链表，如sorted()。

	 除上面第一节Sequence和第二节mutable类型支持的操作符外，链表还支持sort方法：
**** *sort* (*, key=None,reverse=None)
	  元素见比较时，仅能使用“<”比较。如果比较过程中出现语义错误，如“1
	  < 'a'”，则整个排序过程终止（可能将原链表部分排序）。

	  key和reverse参数仅能以关键字参数的形式出现。

	  key参数为接受一个参数的函数，用来指定各元素比较内容，如
	  "key=str.lower"。此函数只在每个元素调用一次。默认值为None，表示
	  不计算每个元素中的key值。

	  如果reverse参数为True，则逆序排序。

	  同reverse函数一样，为保证操作大型sequence时的效率，排序直接改变
	  原来链表，也不返回排序后的链表。（可使用sorted()函数创建一个排序
	  后的新链表实例。）
** 元组（Tuple）
	元组是immutable类型的Sequence；常用来将类型不同的数据存储在一起，
	如内置函数enumarate()的返回的2元素元组；有时也用于存储immutable类
	型的Sequence，如作为set或dict的元素。？

*** class *tuple* ([iterable])
	 构造元组有下面方法：

	 - 一对小括号表示空元组：()。
	 - 在原始后面加逗号表示一元素元组，可无小括号：a,或(a,)。
	 - 多个元素间用逗号隔开，可无小括号：a,b,c或(a,b,c)。
	 - 使用内置tuple构造器函数：tuple或tuple(iterable)。

	 最后一种方法构造的元组，其元素的顺序与参数iterable中的顺序相同。
	 iterable可为Sequence、支持迭代的容器或iterator对象。如果iterable
	 本来就是元组，则同链表一样，也是复制其reference，如果无参数则生成
	 空元组：

	 #+BEGIN_EXAMPLE python
       >>> t = ([1],[2],[3])
       >>> t
       ([1], [2], [3])
       >>> s = tuple(t)
       >>> s
       ([1], [2], [3])
       >>> t[0].append(1)
       >>> t
       ([1, 1], [2], [3])
       >>> s
       ([1, 1], [2], [3])

       # 元组与链表转换时也只是复制其reference
       >>> t
       ([1], [2], [3])
       >>> t = [[1],[2],[3]]
       >>> s = tuple(t)
       >>> s
       ([1], [2], [3])
       >>> s[0].append(1000)
       >>> s
       ([1, 1000], [2], [3])
       >>> t
       [[1, 1000], [2], [3]]
	 #+END_EXAMPLE

	 *注意* ：实际上是逗号，而非小括号构成的元组。小括号基本可省略，单
	 在造成语义混淆的地方不可少，如f(a,b,c)为函数调用3个参数，二
	 f((a,b,c))则是调用了一个3元素元组参数。

	 元组支持前面第一节中，所有Sequence通用操作符。

	 对于内涵不同类型元素的元组，可使用collections.namedtuple()类型实
	 现通过字符串名称获取索引，比纯数字索引更合适。
** 范围（Range）
	range类型为immutable的数字Sequence，常与for语句搭配表示循环次数。
*** class *range* (stop)
*** class *range* (start,stop[,step])
	 所有参数都须为整数（内置int类型或有__index__方法的对象）。如果
	 无step参数，默认为1；如果无start参数，默认为0；如果step参数为0，
	 则返回ValueError错误。下面为range的用法举例：

	 #+BEGIN_EXAMPLE python
       >>> list(range(10))
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
       >>> list(range(1, 11))
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
       >>> list(range(0, 30, 5))
       [0, 5, 10, 15, 20, 25]
       >>> list(range(0, 10, 3))
       [0, 3, 6, 9]
       >>> list(range(0, -10, -1))
       [0, -1, -2, -3, -4, -5, -6, -7, -8, -9]
       >>> list(range(0, -10, 1))
       []
       >>> list(range(0))
       []
       >>> list(range(1, 0))
       []
	 #+END_EXAMPLE

	 除拼接和复制外，range支持上面第一小节中所有Sequence支持的操作。原
	 因为range对象只能表示严格模式的Sequence，拼接和复制会损坏此模式。

	 range对象有start、stop和step3属性，分别对应创建时的三个值：

	 #+BEGIN_EXAMPLE python
       >>> r = range(1, 20, 5)
       >>> r.start
       1
       >>> r.stop
       20
       >>> r.step
       5
	 #+END_EXAMPLE

	 较之链表和元组，range占用内存更小。无论表示序列个数多少，所占内存
	 固定：只存储start、stop和step3个值，各元素需要时才计算。

	 range实现了collections.abc.Sequence ABC，支持元素包含测试，索引查
	 找，截断和负截断：

	 #+BEGIN_EXAMPLE python
       >>> r = range(0, 20, 2)
       >>> r
       range(0, 20, 2)
       >>> 11 in r
       False
       >>> 10 in r
       True
       >>> r.index(10)
       5
       >>> r[5]
       10
       >>> r[:5]
       range(0, 10, 2)
       >>> r[-1]
       18
	 #+END_EXAMPLE

	 使用==和!=判断range是否相等时，同一般Sequence一样，即两者中元素是
	 否逐个相等。两个相等的range可有不同的start、stop和step值，如
	 range(0) == range(2, 1, 3)。

* 文本Sequence类型-str
   Python中文本数据使用字符串(str/strings)对象存储。字符串对象为
   immutable类型的Sequence，其中元素为"Unicode code point"。字符串对象
   可用下面方式表示：

   - 单引号：'里面可用"双引号"'。
   - 双引号："里面可有'单引号'"。
   - 三引号：'''可以是三个单引号'''，"""也可以是三个双引号"""。

   三引号表示的字符串可跨行书写，且保留换行符。

   在同一个表达式中，如果字符串间只有空格，则字典拼接：("spam"
   "eggs") == "spam eggs"。

   由于Python并没有字符类型，所以使用索引获得字符串的某个元素时，返回
   值为长度为1的字符串。所以，对于非空字符s，有s[0] == s[0:1]。

   由于字符串本身为immutable，为保证效率，可拼接字符串时可使用
   str.join()和io.StringIO方法。

   - class *str* (object='')
   - class *str* (object='', encoding='utf-8',errors='strict')
	 返回object的字符串形式。如果无object参数，返回空字符串；否则，返
     回值由下面规则决定：

	 如果encoding和errors参数都没有，返回值实际上是object.__str__()方
     法的返回值。对于字符串对象，则是返回该字符串本身；如果
     object无__str__()方法，则是返回调用repr(object)函数的返回值。

	 如果encoding和errors中只要出现任意一个，object就须为类bytes对象
     （bytes或bytearray）。此时，str(bytes, encoding, errors)相当于
     bytes.decode(encoding, errors)。

	 将bytes对象传递给str()函数，且不带encoding和errors参数时，返回"非
     正式"字符串：

	 #+BEGIN_EXAMPLE python
       >>> str(b'Zoot')
       "b'Zoot'"
	 #+END_EXAMPLE

** 字符串方法
	字符串类型支持第一节中所有Sequence常用的操作，此外还支持下面列举的
	操作。

	字符串支持两种格式化方法：str.format()方法，和与C中printf类似的方
	法。
*** str. *capitalize* ()
	 返回复制后的字符串，第一个字母大写，其余字母小写。
*** str. *casefold* ()
	 相当于str.lower()方法。[[http://www.cnblogs.com/zhanmeiliang/p/5988207.html][@爱尔兰时空]]：

	 lower()只对'A-Z'有效，不能处理其他语言中小写的问题，如德语中'ß'的
	 小写为'ss'：

	 #+BEGIN_EXAMPLE python
       >>> s = 'ß'
       >>> s.lower()
       'ß'
       >>> s.casefold()
       'ss'
	 #+END_EXAMPLE
*** str. *center* (width[,fillchar])
	 将字符串扩展为长度width，原字符串至于中间，空白处使用fillchar字符
	 填充（默认为ASCII空格字符），如果width小于或等于len(s)，则返回原
	 来字符串：

	 #+BEGIN_EXAMPLE python
       >>> s = 'claudio'
       >>> s.center(10)
       ' claudio  '
       >>> s.center(10, '|')
       '|claudio||'
       >>> s.center(1)
       'claudio'
	 #+END_EXAMPLE

*** str. *count* (sub[,start[,end]])
	 返回字符串sub出现的次数，可指定在截断[start:end]间计算：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.count('an')
       2
       >>> s.count('an', -3)
       1
       >>> s.count('an', 3)
       1
	 #+END_EXAMPLE

*** str. *encode* (encoding='utf-8',errors='strict')
	 以bytes对象的形式返回字符串编码后的结果。默认编码为utf-8；默认
	 errors值为strict，即当出现编码错误时返回UnicodeError错误，其他可
	 取值为ignore、replace、xmlcharrefreplace和backslashreplace，以及
	 其他通过codecs.register_error()方法寄存的名称。

	 #+BEGIN_EXAMPLE python
       >>> 'claudio'.encode()
       b'claudio'
       >>> '学习'.encode()
       b'\xe5\xad\xa6\xe4\xb9\xa0';
	 #+END_EXAMPLE

*** str. *endswith* (suffix,[,start[,end]])
	 如果字符串以suffix结尾返回True，否则返回False。可指定在截断
	 [start:end]中计算：

	 #+BEGIN_EXAMPLE
       >>> 'banana'.endswith('na')
       True
       >>> 'banana'.endswith('na', 5)
       False
       >>> '香蕉'.endswith('蕉')
       True
	 #+END_EXAMPLE
*** str. *expandtabs* (tabsize=8)
	 返回复制后的字符串，其中tab字符使用一个或多个空格替代，可指定一个
	 tab字符所占列数：

	 #+BEGIN_EXAMPLE python
       >>> '01\t012\t0123\t01234'.expandtabs()
       '01      012     0123    01234'
       >>> '01\t012\t0123\t01234'.expandtabs(4)
       '01  012 0123    01234'
	 #+END_EXAMPLE
*** str. *find* (sub[,start[,end]])
	 返回从左到右起，sub出现在字符串中的索引，可指定在截断[start:end]
	 中计算，如果无sub字符串出现，则返回-1。

	 #+BEGIN_EXAMPLE python
       >>> 'banana'.find('a')
       1
       >>> 'banana'.find('a', 4)
       5
       >>> 'banana'.find('a', 19)
       -1
	 #+END_EXAMPLE

	 为效率考虑，只有需知道sub在字符串中的索引时才使用find()方法，如果
	 只是判断是否出现sub，使用in操作符即可：

	 #+BEGIN_EXAMPLE python
       >>> 'Py' in 'Python'
       True
       >>> 'py' in 'Python'
       False
	 #+END_EXAMPLE

*** str. *format* (*args,**kwargs)
	 对字符串进行格式化。字符串中可含普通字符，也可含需被替换的place
	 holder，用{}表示。{}中可为数字或关键字参数，分别对应format中的
	 args和kwargs：

	 #+BEGIN_EXAMPLE python
       >>> 'The sum of 1 + 2 is {0}'.format(1+2)
       'The sum of 1 + 2 is 3'
       >>> 'The sum of {a} + {b} is {0}'.format(1+2, a=1, b=2)
       'The sum of 1 + 2 is 3'
	 #+END_EXAMPLE

	 如需打印大括号本身，使用双层大括号：

	 #+BEGIN_EXAMPLE python
       >>> 'format 中使用{{}}表示placeholder'.format()
       'format 中使用{}表示placeholder'
	 #+END_EXAMPLE

*** str. *format_map* (mapping)
	 与str.format(***mapping)类型，不过是直接使用mapping，而不是复制到
	 dict中。如果mapping本身就是dict的一个子类，则非常方便。？？？：

	 #+BEGIN_EXAMPLE
       >>> d = {'name': 'Guido'}
       >>> '{name} was born in ?'.format(**d)
       'Guido was born in ?'

       >>> class Default(dict):
       ...     def __missing__(self, key):
       ...             return key
       ...
       >>> '{name} was born in {country}'.format_map(Default(name='Guido'))
       'Guido was born in country'
	 #+END_EXAMPLE

*** str. *index* (sub[,start[,end]])
	 同find()方法类似，不过当不能在字符串中找到sub时返回ValueError错误，
	 而非-1：

	 #+BEGIN_EXAMPLE
       >>> 'banana'.index('a')
       1
       >>> 'banana'.index('aD')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         ValueError: substring not found
	 #+END_EXAMPLE

*** str. *isalnum* ()
	 如果字符串不为空，且其中所有字符非数字即"字母"，则返回True：

	 #+BEGIN_EXAMPLE
       >>> '111'.isalnum()
       True
       >>> ''.isalnum()
       False
       >>> '11#'.isalnum()
       False
	 #+END_EXAMPLE

	 只要c.isalpha()、c.isdecimal()、c.isdigit()或c.isnumeric()中一个
	 返回True，则c.isalnum()就返回True。

*** str. *isalpha* ()
	 如果字符串中不为空，且所有字符窦唯“字母”则返回True。只要Unicode字
	 符数据库中认为是"字母"都可。

	 *注意* ：不同于Unicode Standard中定义的"Alphabetic"。

	 #+BEGIN_EXAMPLE python
       >>> 'a'.isalpha()
       True
       >>> '一'.isalpha()
       True
	 #+END_EXAMPLE
*** str. *isdecimal* ()
	 字符串不为空，且所有字符都是十进制数字符，即所有能用于表示十进制
	 数的字符。
*** str. *isdigit* ()
	 除isdecimal字符外，还包含“compatibility superscript digits”。？？？
*** str. *isidentifier* ()
	 如果是Python中合法的identifier（变量名、函数名和类名），则返回
	 True：

	 #+BEGIN_EXAMPLE python
       >>> 'is_identifer'.isidentifier()
       True
       >>> 'is-identifer'.isidentifier()
       False
       >>> 'is2identifer'.isidentifier()
       True
       >>> '_is_identifer'.isidentifier()
       True
       >>> '_is_identifer#'.isidentifier()
       False
	 #+END_EXAMPLE

	 如需判断是否是“保留字”，使用keuword.iskeyword()方法：

	 #+BEGIN_EXAMPLE python
       >>> import keyword
       >>> keyword.iskeyword('def')
       True
       >>> keyword.iskeyword('class')
       True
       >>> keyword.iskeyword('name')
       False
       >>> keyword.iskeyword('__init__')
       False
	 #+END_EXAMPLE
*** str. *islower* ()
	 含至少一个有大小写区分的字符，且所有有大小写区别的字符都为小写：

	 #+BEGIN_EXAMPLE
       >>> 'abc'.islower()
       True
       >>> ''.islower()
       False
       >>> 'ab三'.islower()
       True
       >>> 'ab3'.islower()
       True
       >>> '一'.islower()
       False
	 #+END_EXAMPLE

*** str. *isnumeric* ()？？？
	 字符串不为空，且所有字符都为数字字符：

	 #+BEGIN_EXAMPLE python
       >>> '012'.isnumeric()
       True
       >>> '0X12'.isnumeric()
       False
       >>> '0x12'.isnumeric()
       False
	 #+END_EXAMPLE

	 *？* ：和isdigit的区别。

*** str. *isprintable* ()
	 只含所有可见字符+空格字符，以及空字符串返回True：

	 #+BEGIN_EXAMPLE python
       >>> ' '.isprintable()
       True
       >>> '\n '.isprintable()
       False
       >>> ''.isprintable()
       True
	 #+END_EXAMPLE
*** str. *isspace* ()
	 所有空白字符。
	 #+BEGIN_EXAMPLE python
       >>> ''.isspace()
       False
       >>> ' '.isspace()
       True
       >>> '\n\t'.isspace()
       True
	 #+END_EXAMPLE
*** str. *istitle* ()
	 含至少一个字符，为标题形式的字符串返回True。

	 #+BEGIN_EXAMPLE
       >>> 'I Have A Dream'.istitle()
       True
       >>> 'I Have a Dream'.istitle()
       False
       >>> 'I HAVE A Dream'.istitle()
       False
       >>> 'I HavE A Dream'.istitle()
       False
       >>> '我是标题'.istitle()
       False
       >>> 'The Way to Go'.istitle()
       False
	 #+END_EXAMPLE
*** str. *isupper* ()
	 含至少一个有大小写区分的字符，且所有区分大小写的字符都为大写。
*** str. *join* (iterable)
	 使用字符串将iterable中的所有元素拼接，如果任何一个元素不为字符串
	 （含bytes类型），则返回Valueerror错误。

	 #+BEGIN_EXAMPLE python
       >>> '|'.join(['a','b','c'])
       'a|b|c'

       >>> '|'.join(['a','b',3])
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         TypeError: sequence item 2: expected str instance, int found
       >>> '|'.join(['a','b',b'c'])
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         TypeError: sequence item 2: expected str instance, bytes found

       >>> '|'.join([])
       ''
	 #+END_EXAMPLE
*** str. *ljust* (width[,fillchar])
	 返回指定宽带为width，左对齐后的字符串，使用fillchar填充空白字符。
	 如果width<=len(s)则返回原来字符串。

	 #+BEGIN_EXAMPLE python
       >>> 'claudio'.ljust(10)
       'claudio   '
       >>> 'claudio'.ljust(10, '|')
       'claudio|||'
       >>> 'claudio'.ljust(1, '|')
       'claudio'
	 #+END_EXAMPLE
*** str. *lower* ()
	 返回复制后的字符串，并将所有有大小写区别的字符转换为小写。
*** str. *lstrip* ([chars])
	 返回复制后的字符串，将左边的含chars中字符的所有字符删除，如果参数
	 为None，则char默认为' '。

	 *注意* ：chars不是前缀，而是单个字符的组合：

	 #+BEGIN_EXAMPLE python
       >>> '   i have a dream    '.lstrip()
       'i have a dream    '
       >>> 'www.bing.com'.lstrip('w.com')
       'bing.com'
	 #+END_EXAMPLE
*** static str. *maketrans* (x[,y[,z]])
	 此方法为静态方法。作用是返回一个用于str.translate()方法翻译字符串
	 的字典类型。

	 如果只有一个参数，则须为字典型，key值可为单个字符字符串或Unocide
	 值，value值可为单个字符字符串、Unicode值，任意长度字符串或None。

	 如果是两个参数，则须为长度相等的字符串，对应位置的字符分别成为生
	 成字典的key值和value值。

	 如果是三个参数，最后一个参数需为字符串，其中的字符为会成为生成字
	 典的key值，对应的value值则为None，即使用str.translate()方法时将删
	 除的字符：

	 #+BEGIN_EXAMPLE python
       >>> str.maketrans({'a': '98'})
       {97: '98'}
       >>> str.maketrans({'a': 98})
       {97: 98}
       >>> str.maketrans({'a': None})
       {97: None}
       >>> str.maketrans({97: 'qw' })
       {97: 'qw'}

       >>> str.maketrans('aeiou', '123')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         ValueError: the first two maketrans arguments must have equal length
       >>> str.maketrans('aeiou', '12345')
       {97: 49, 111: 52, 117: 53, 101: 50, 105: 51}
       >>> str.maketrans('aeiou', '12345', 'XZ')
       {97: 49, 117: 53, 88: None, 105: 51, 90: None, 101: 50, 111: 52}

	 #+END_EXAMPLE
*** str. *partition* (sep)
	 将字符串在第一次出现sep时分割，返回一个3元素元组，其中第一个元素
	 为sep前面的字符串，第二个元素为sep本身，第三个元素为后面的字符串。
	 如果字符串中不含sep，则第一个元素为字符串本身，后面两个元素为空字
	 符串：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.partition('a')
       ('b', 'a', 'nana')
       >>> s.partition('an')
       ('b', 'an', 'ana')
       >>> s.partition('X')
       ('banana', '', '')
       >>> s.partition('')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         ValueError: empty separator
	 #+END_EXAMPLE
*** str. *replace* (old,new[,count])
	 将字符串中所有的old都替换为new。如果有count参数，则只替换左起
	 count个：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.replace('an', 'AN')
       'bANANa'
       >>> s.replace('an', 'AN', 1)
       'bANana'
       >>> s.replace('an', 'AN', 100)
       'bANANa'
       >>> s.replace('an', 'AN', 0)
       'banana'
       >>> s.replace('an', 'AN', -1)
       'bANANa'
       >>> s.replace('an', 'AN', -2)
       'bANANa'
	 #+END_EXAMPLE
*** str. *rfind* (sub[,start[,end]])
	 返回从右其字符串中第一次出现sub的索引，可指定在截断[start:end]中
	 计算。如果无sub字符串出现，则返回-1：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.rfind('a')
       5
       >>> s.rfind('A')
       -1
       >>> s.rfind('a', -4, -2)
       3
	 #+END_EXAMPLE
*** str. *rindex* (sub[,start[,end]])
	 同rfind，不过如果无sub字符串出现返回ValueError错误：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.rindex('a')
       5
       >>> s.rindex('A')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         ValueError: substring not found
	 #+END_EXAMPLE

*** str. *rjust* (width[,fillchar])
	 返回右对齐后的字符串，使用fillchar填充空白字符，默认为空格字符。
	 如果width小于或等于len(s)，则返回字符串本身：

	 #+BEGIN_EXAMPLE python
       >>> 'claudio'.rjust(10)
       '   claudio'
       >>> 'claudio'.rjust(10, '|')
       '|||claudio'
       >>> 'claudio'.rjust(1, '|')
       'claudio'
	 #+END_EXAMPLE
*** str. *rpartition* (sep)
	 同str.partition，不过是从右起分割；且如果sep不出现在字符串中，返
	 回的3元素元组前两个元素为空字符串，最后一个为字符串本身：

	 #+BEGIN_EXAMPLE python
       >>> s = 'banana'
       >>> s.rpartition('a')
       ('banan', 'a', '')
       >>> s.rpartition('n')
       ('bana', 'n', 'a')
       >>> s.rpartition('X')
       ('', '', 'banana')
	 #+END_EXAMPLE
*** str. *rsplit* (sep=None,maxsplit=-1)
	 与split函数相同，只是从右边分割。

	 *？* ：既然有split函数，此函数还有啥子卵用？

*** str. *rstrip* ([chars])
	 返回字符串的副本，末尾中的字符只要出现在chars则被移除。如果无
	 chars参数，或为None，则默认移除末尾的空白字符。

	 *注意* ：chars不是后缀，而是所有需移除字符的集合。

	 #+BEGIN_EXAMPLE
       >>> 'www.bing.com'.rstrip('w.com')
       'www.bing'
	 #+END_EXAMPLE

*** str. *split* (sep=None,maxsplit=-1)
	 返回字符串中所有“单词”组成的链表，使用sep作为单词间的分隔符。如果
	 指定maxsplit参数，则进行maxsplit次分割（即结果最多可有maxsplit+1
	 个元素）；如果未指定maxsplit参数，或其值为-1，则最大限度分割。

	 #+BEGIN_EXAMPLE
       >>> s = 'banana'
       >>> s.split('a')
       ['b', 'n', 'n', '']
       >>> s.split('a', 1)
       ['b', 'nana']
	 #+END_EXAMPLE

	 如果有sep参数，连续的分割字符串间会生成空白字符：

	 #+BEGIN_EXAMPLE python
       >>> '1,,2'.split(',')
       ['1', '', '2']
	 #+END_EXAMPLE

	 分割字符串可为多个字符：

	 #+BEGIN_EXAMPLE python
       >>> '1<>2<>3'.split('<>')
       ['1', '2', '3']
	 #+END_EXAMPLE

	 如果指定sep参数，且字符串为空，则生成的链表只含一个空字符串；如果
	 不指定sep参数，且原字符串为空，或只含空白字符，则返回控链表：

	 #+BEGIN_EXAMPLE python
       >>> ''.split()
       []
       >>> ''.split(',')
       ['']

       >>> '   '.split()
       []
	 #+END_EXAMPLE

	 如果无sep参数，或为None，则使用不同的算法：使用空白字符作为分割字
	 符，且删除相邻的空字符，即使首位有空格，返回的链表中也不会含空字
	 符串：

	 #+BEGIN_EXAMPLE python
       >>> '1 2 3'.split()
       ['1', '2', '3']
       >>> '1 2 3'.split(maxsplit=1)
       ['1', '2 3']
       >>> '1     2  3'.split()
       ['1', '2', '3']
	 #+END_EXAMPLE

*** str. *splitlines* ([keepends])
	 在字符串中换行符处分割，返回链表。下表中的字符都会被当做换行符：

     | 字符     | 含义 |
     |----------+------|
     | \n       |      |
     | \r       |      |
     | \r\n     |      |
     | \v或\x0b |      |
     | \f或\x0c |      |
     | \x1c     |      |
     | \x1d     |      |
     | \x1e     |      |
     | \x85     |      |
     | \u2028   |      |
     | \u2029   |      |

	 #+BEGIN_EXAMPLE python
       >>> 'ab c\n\rde fd\rkl\r\n'.splitlines()
       ['ab c', '', 'de fd', 'kl']
	 #+END_EXAMPLE

	 结果中如需包含各种换行符，可指定keppends：

	 #+BEGIN_EXAMPLE python
       >>> 'ab c\n\rde fd\rkl\r\n'.splitlines(keepends=True)
       ['ab c\n', '\r', 'de fd\r', 'kl\r\n']
       >>> 'ab c\n\rde fd\rkl\r\n'.splitlines(keepends='\n')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         TypeError: an integer is required (got type str)
	 #+END_EXAMPLE

	 不同于split()函数，如果指定sep参数，且原字符串为空，此函数返回空
	 链表，末尾的换行符后并不生成一个空字符串：

	 #+BEGIN_EXAMPLE python
       >>> ''.splitlines()
       []
       >>> 'One line\n'.splitlines()
       ['One line']
	 #+END_EXAMPLE

	 而split('\n')的对应结果为：

	 #+BEGIN_EXAMPLE
       >>> ''.split('\n')
       ['']
       >>> 'One line\n'.split('\n')
       ['One line', '']
	 #+END_EXAMPLE

*** str. *startswith* (prefix[,start[,end]])
	 如果字符串有前缀prefix，则返回True，可指定在截断[start:end]中计算：

	 #+BEGIN_EXAMPLE python
       >>> 'banana'.startswith('b')
       True
       >>> 'banana'.startswith('a')
       False
       >>> 'banana'.startswith('')
       True
       >>> 'banana'.startswith('n', 2)
       True
	 #+END_EXAMPLE
*** str. *strip* ([chars])
	 返回原字符串副本，移除收尾中在chars中出现的字符。如果无chars参数，
	 或为None，则默认删除首尾的空白字符。

	 *注意* ：chars不是前缀或后缀，而是所有需移除字符的集合。

	 #+BEGIN_EXAMPLE
       >>> 'www.bing.com'.strip('w.com')
       'bing'
	 #+END_EXAMPLE

*** str. *swapcase* ()

	 返回大小写交换后的字符串副本。

	 *注意* ：s.swapcase().swapcase() 可能并不等于s。

	 #+BEGIN_EXAMPLE
       >>> s = 'Banana'
       >>> s.swapcase()
       'bANANA'
       >>> s.swapcase().swapcase()
       'Banana'

       >>> s = '一二三'
       >>> s.swapcase()
       '一二三'
       >>> s.swapcase().swapcase()
       '一二三'

       >>> s = 'ß'
       >>> s.swapcase()
       'SS'
       >>> s.swapcase().swapcase()
       'ss'
	 #+END_EXAMPLE
*** str. *title* ()
	 将原字符串中每个单词首字母大写，其他字母小写作为返回值：

	 #+BEGIN_EXAMPLE python
       >>> 'i have a dream'.title()
       'I Have A Dream'
       >>> 'I Have a Dream'.title()
       'I Have A Dream'
       >>> '我有一个梦想'.title()
       '我有一个梦想'
	 #+END_EXAMPLE

	 *注意* ：此函数只将连续字母看做"单词"，所以可能结果不能如愿：

	 #+BEGIN_EXAMPLE
       >>> "they'are bill's friends from the UK".title()
       "They'Are Bill'S Friends From The Uk"
	 #+END_EXAMPLE

	 可使用正则勉强解决：

	 #+BEGIN_SRC python
       #!/usr/bin/python3.5
       import re

       def titlecase(s):
           return re.sub(r"[A-Za-z]+('[A-Za-z]+)?",
                         lambda mo: mo.group(0)[0].upper() + mo.group(0)[1:].lower(),
                         s)

       print(titlecase("they're bill's friends from UK"))
       # They're Bill's Friends From Uk
	 #+END_SRC

*** str. *translate* (table)
	 将字符串中的字符逐个与参数table中的元素对应，如果相同，则转换，返
	 回转换后的结果。可使用静态方法str.maketrans(in, out)创建字典：

	 [[http://www.runoob.com/python/att-string-translate.html][@runoob]]：

	 #+BEGIN_EXAMPLE python
       >>> str = 'a a'
       >>> intab = 'aeiou'
       >>> outtab = '12345'
       >>> tantab = str.maketrans(intab, outtab) #创建翻译字典
       >>> tantab
       {97: 49, 111: 52, 117: 53, 101: 50, 105: 51}
       >>> str = 'this is a string example...wow!!!'
       >>> str.translate(tantab)       #翻译
       'th3s 3s 1 str3ng 2x1mpl2...w4w!!!'
	 #+END_EXAMPLE

	 table参数须为通过__getitem__()方法实现索引的对象，即mapping或
	 sequence对象。当字典key值为整数时，可翻译为：单个字符、Unicode值；
	 如果为None则删除原来字符。

	 #+BEGIN_EXAMPLE python
       >>> str = 'a a'
       >>> str.translate({97:'A'})
       'A A'
       >>> str.translate({97:'ABC'})
       'ABC ABC'
       >>> str.translate({97: None})
       ' '
       >>> str.translate({97: 'A'})
       'A A'
       >>> str.translate({97: 1234})
       'Ӓ Ӓ'
	 #+END_EXAMPLE

*** str. *upper* ()
	 返回字符串副本，将有大小写区别的字符转换为大写。

	 *注意* ：如果str中只含无大小写区分字符，str.upper().isupper()可能
	 返回False：

	 #+BEGIN_EXAMPLE python
       >>> '测试'.isupper()
       False
       >>> 'abc测试'.upper().isupper()
       True
       >>> '测试'.upper().isupper()
       False
	 #+END_EXAMPLE

*** str. *zfill* (width)
	 返回字符串副本，使用ASCII'0'填充扩张到width长度后的左边的空白。如果有正
	 负号，则先添加。如果width小于或等于len(s)则返回字符串本身：

	 #+BEGIN_EXAMPLE python
       >>> '42'.zfill(5)
       '00042'
       >>> '-42'.zfill(5)
       '-0042'
       >>> '-qwdqw'.zfill(5)
       '-qwdqw'
	 #+END_EXAMPLE

** printf风格的格式化输出
	*注意* ：最好使用str.format()接口格式化字符串。

* 二进制Sequence类型-bytes、bytearray、menoryview
   bytes和bytearray是Python核心内置处理二进制数据的类。由memoryvie类
   支持，此类使用"缓存协议（buffer protocol）"，不用复制就可获得其他
   对象的内存地址。？

   array模块支持高效率存储基本数据类型，如32位整数和IEEE754双精度浮点
   数。

** 写在前面
*** 用处举例 [[http://blog.csdn.net/hanhuili/article/details/9069507][@李寒辉的技术日记]]
	 比如对字符串进行加密处理，通常是逐个处理字符串中的单个字节。如果
	 只含ASCII字符，直接遍历就可；单如果有非ASCII字符，这些字符可能占
	 多个字节，就不能通过遍历每个字符来实现遍历每个字节。
*** 进一步说明 [[https://segmentfault.com/a/1190000004450876][@xu_zhoufeng]]
	 Bytes类似字符串，不过是由单个字节（8位，取值范围为0-255）作为基本
	 元素的Sequence类型，也为Immutable。

	 Bytes对象的形式为b'xxxx'，其中x为单个字节。单个字节的表示方式为
	 \xHH，其中\x为16进制转义符，HH为16进制数（取值范围为10进制的
	 0-255）。对于同一字符串，使用不同编码形式生成的Bytes对象，就会有
	 不同的值：

	 #+BEGIN_EXAMPLE python
       >>> s = 'a1一'
       >>> b = bytes(s, 'utf-8')
       >>> b
       b'a1\xe4\xb8\x80'
       >>> c = bytes(s, 'gb2312')
       >>> c
       b'a1\xd2\xbb'
	 #+END_EXAMPLE

	 上例将字符串s分别使用utf-8和gb2312编码转换为了Bytes对象b和c。由于
	 编码不同，长度也不同：

	 #+BEGIN_EXAMPLE
       >>> len(b)
       5
       >>> len(c)
       4
	 #+END_EXAMPLE

	 使用Bytes对象的decode方法就可实现解码，如果编码参数与编码时相同，
	 就会与原来相同的字符，否则就可能返回UnicodeDecodeError错误：

	 #+BEGIN_EXAMPLE python
       >>> b.decode('utf-8')
       'a1一'
       >>> c.decode('gb2312')
       'a1一'

       >>> b.decode('gb2312')
       Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         UnicodeDecodeError: 'gb2312' codec can't decode byte 0x80 in position 4: incomplete multibyte sequence
	 #+END_EXAMPLE

	 可通过字面量形式创建Bytes对象，不过仅限于ASCII范围内的字符：

	 #+BEGIN_EXAMPLE python
       >>> d = b'1a一'
         File "<stdin>", line 1
         SyntaxError: bytes can only contain ASCII literal characters.
         >>> d = b'1a'
         >>> d
         b'1a'
	 #+END_EXAMPLE

** Bytes对象
	bytes对象是由单个bytes元素组成的immutable类型的Sequence。由于主要
	的二进制协议都基于ASCII文本编码，bytes对象中有几个方法只在处理
	ASCII兼容数据时有效，且与字符串的一些方法用法相似。

	bytes对象字面量与字符串字面量唯一区别是在前面有b字母：

	- 单引号：b'still allows embedded "double" quotes'
	- 双引号：b"still allows embedded 'single' quotes"
	- 三引号：'''3 single quotes'''，b"""3 double quotes"""

	不管源代码编码声明如何，字面量中只允许存在ASCII字符，任何Unicode值
	大于127的字符都需转义表示。

	同字符串字面量相同，可在添加前缀r，指定不处理转义序列？：

	#+BEGIN_EXAMPLE python
      >>> s = r'a\nb'
      >>> s
      'a\\nb'
      >>> print(s)
      a\nb
      >>> s = 'a\nb'
      >>> print(s)
      a
      b

      >>> b = b'a\nb'
      >>> print(b)
      b'a\nb'
      >>> b = br'a\nb'
      >>> print(b)
      b'a\\nb'
	#+END_EXAMPLE

	尽管bytes字面量的表示基于ASCII文本，但bytes对象实际上更像immutable
	类型的整数序列，其中元素的取值范围为0<=x<256。

	除字面量外，还可使用一下方法创建bytes对象：

	- 指定长度，所有元素用0初始化：bytes(0)。
	- 转换至只含整数的iterable：bytes(rang(20))。
	- 通过buffer协议复制二进制数据：bytes(obj)。
	- 参考bytes函数

	由于2位的16进制数就可表示一个字节，所以常使用16进制数表示二进制数。
	因此，bytes对象可使用fromhex类方法将字符串转换为bytes对象。

	classmethod bytes. *fromhex* (string)：解码字符串，忽视空格，返回
	bytes对象：

	#+BEGIN_EXAMPLE python
      >>> bytes.fromhex('')
      b''
      >>> bytes.fromhex('2ef0 F1F2   ')
      b'.\xf0\xf1\xf2'
	#+END_EXAMPLE

	bytes. *hex* ()：将bytes对象转换为16进制形式的字符串：

	#+BEGIN_EXAMPLE python
      >>> b'\xf0\xf1\xf2'.hex()
      'f0f1f2'
	#+END_EXAMPLE

	与字符串对象不同的是，如果b为bytes对象，b[0]会返回整数，b[0:1]会返
	回长度为1的bytes对象。

	b'...'形式表示比bytes([46, 46, 46])更有用，不过还是可使用list函数
	将bytes对象转换为整数链表。

** Bytearray对象
	bytearray对象相当于immutable形式的bytes对象。不过没有相应的字面量
	表示方法，只可用构造器函数构造：

	- 创建空实例：bytearray()
	- 指定长度，使用0填充每个元素：bytearray(10)
	- 使用只含整型iterable类型：bytearray(range(20))
	- 通过buffer协议复制二进制数据：bytearray(b'Hi!')

	bytearray支持所有前面中所有mutable类型Sequence支持的操作，以
	及后面将介绍的bytes和bytearray常见的操作。

	与bytes一样，bytearray也有类方法fromhex()和方法hex()：

	#+BEGIN_EXAMPLE python
      >>> bytearray.fromhex('2Ef0 F1f2')
      bytearray(b'.\xf0\xf1\xf2')
      >>> bytearray(b'\xf0\xf1\xf2').hex()
      'f0f1f2'
	#+END_EXAMPLE

	同样也可使用list函数转换为整数链表：

	#+BEGIN_EXAMPLE python
      >>> b = bytearray(b'...')
      >>> list(b)
      [46, 46, 46]
	#+END_EXAMPLE

** Bytes和bytearray操作符
*** bytes. *count* (sub[,start[,end]])
*** bytearray. *count* (sub[,start[,end]])
*** bytes. *decode* (encoding='utf-8',errors='strict')
*** bytearray. *decode* (encoding='utf-8',errors='strict')
*** bytes. *endswith* (suffix[,stat[,end]])
*** bytearray. *endswith* (suffix[,stat[,end]])
*** bytes. *find* (sub[,start[,end]])
*** bytearray. *find* (sub[,start[,end]])
*** bytes. *index* (sub[,start[,end]])
*** bytearray. *index* (sub[,start[,end]])
*** bytes. *join* (iterable)
*** bytearray. *join* (iterable)
*** static bytes.maketrans(from, to)
*** static bytearray.maketrans(from, to)
*** bytes. *partition* (sep)
*** bytearray. *partition* (sep)
*** bytes. *replace* (old, new, [count])
*** bytearray. *replace* (old, new, [count])
*** bytes. *rfind* (subp[,start[,end]])
*** bytearray. *rfind* (subp[,start[,end]])
*** bytes. *rindex* (sub[,start[,end]])
*** bytearray. *rindex* (sub[,start[,end]])
*** bytes. *rpartition* (sep)
*** bytearray. *rpartition* (sep)
*** bytes. *startswith* (prefix,[start[,end]])
*** bytearray. *startswith* (prefix,[start[,end]])
*** bytes. *translate* (table[,delete])
*** bytearray. *translate* (table[,delete])
*** bytes. *center* (width[,fillchar])
*** bytearray. *center* (width[,fillchar])
*** bytes. *ljust* (width[,fillchar])
*** bytearray. *ljust* (width[,fillchar])
*** bytes. *lstrip* ([chars])
*** bytearray. *lstrip* ([chars])
*** bytes. *rjust* (width[,fillchar])
*** bytearray. *rjust* (width[,fillchar])
*** bytes. *rsplit* (sep=None,maxsplit=-1)
*** bytearray. *rsplit* (sep=None,maxsplit=-1)
*** bytes. *rstrip* ([chars])
*** bytearray. *rstrip* ([chars])
*** bytes. *split* (sep=None,maxsplit=-1)
*** bytearray. *split* (sep=None,maxsplit=-1)
*** bytes. *strip* ([chars])
*** bytearray. *strip* ([chars])
*** bytes. *capitalize* ()
*** bytearray. *capitalize* ()
*** bytes. *expandtabs* (tabsize=8)
*** bytearray. *expandtabs* (tabsize=8)
*** bytes. *isalnum* ()
*** bytearray. *isalnum* ()
*** bytes. *isalpha* ()
*** bytearray. *isalpha* ()
*** bytes. *isdigit* ()
*** bytearray. *isdigit* ()
*** bytes. *islower* ()
*** bytearray. *islower* ()
*** bytes. *isspace* ()
*** bytearray. *isspace* ()
*** bytes. *istitle* ()
*** bytearray. *istitle* ()
*** bytes. *isupper* ()
*** bytearray. *isupper* ()
*** bytes. *lower* ()
*** bytearray. *lower* ()
*** bytes. *splitlines* (keepends=False)
*** bytearray. *splitlines* (keepends=False)
*** bytes. *swapcase* ()
*** bytearray. *swapcase* ()
*** bytes. *title* ()
*** bytearray. *title* ()
*** bytes. *upper* ()
*** bytearray. *upper* ()
*** bytes. *zfill* ()
*** bytearray. *zfill* ()
** 使用printf风格格式化Byes
** Memory Views
* Set类型-set、frozenset
* Mapping类型-dict
* Context Manager 类型

* 其他内置类型

* 特殊属性
